# -*- coding: utf-8 -*-
"""Quiz6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Uoznrgttu9XVHcrDDhNDGYY_R3iqjNv
"""
# create function CreateMorseCode
def CreateMorseCode(text):
  morse = {'A':'.-', 'B':'-...', 'C':'-.-.', 'D':'-..', 'E':'.', 'F':'..-.', 'G':'--.', 'H':'....', 'I':'..', 
         'J':'.---', 'K':'-.-', 'L':'.-..', 'M':'--', 'N':'-.', 'O':'---', 'P':'.--.', 'Q':'--.-', 'R':'.-.', 
         'S':'...', 'T':'-', 'U':'..-','V':'...-', 'W':'.--', 'X':'-..-', 'Y':'-.--', 'Z':'--..','1':'.----', 
         '2':'..---', '3':'...--', '4':'....-', '5':'.....', '6':'-....', '7':'--...', '8':'---..', '9':'----.', '0':'-----'}

  code = ""
  for c in text:
    code += morse[c] + " "
  return (code)

message = input("What text do you want to translate to morse code? : ")    # input message 
message = message.upper()                                                  # transform message to a uppercase
output = CreateMorseCode(message)                                          # call function CreateMorseCode
print("The morse code of this text is ", output)
