# -*- coding: utf-8 -*-
"""Quiz5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/164Sq5iv7duD2x8lFIv_B5Ew2zMOG99N_
"""

L = list(range(2))
i = 0
n = int(input("What term of the Fibonacci sequence do you want? : "))

while i < n-2 :
    Lnext = L[0+i]+L[1+i]
    L.append(Lnext)
    i = i + 1
        
print(L)
#len(L)