# -*- coding: utf-8 -*-
"""Quiz4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10sVJvcofPfdnTC80CSZooAM9eFm8pAE0
"""

x = input("What logic do you want to check? : ")
x = x.lower()
#a = True
#b = True

def AND (a,b):
  if a == 1 and b == 1 :
    return(True)
  else :
    return (False)

def OR (a,b):
  if a == 0 and b == 0 :
    return (False)
  else :
    return (True)

def NOT (a):
  if a == 0 :
    return (True)
  elif a == 1 :
    return (False)
  elif b == 0  :
    return (True)
  elif b == 1 :
    return (False)

print("The Truth Table")
print("------------------------------------------------------------------")
print("|        a        |        b       |       ",x , " ")
print("------------------------------------------------------------------")
for a in [True,False]:
  for b in [True,False]:
    print("|      " + str(a) + "       |      " + str(b) + "      |    " + str(f(a,b)) + "    " )
    print("------------------------------------------------------------------")

#print(f(a,b))