# -*- coding: utf-8 -*-
"""Quiz4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10sVJvcofPfdnTC80CSZooAM9eFm8pAE0
"""

x = input("What logic do you want to check? : ")
x = x.lower()
#a = True
#b = True

def f(a,b):
  return(eval(x))

print("The Truth Table")
print("------------------------------------------------------------------")
print("|        a        |        b       |       ",x , " ")
print("------------------------------------------------------------------")
for a in [True,False]:
  for b in [True,False]:
    print("|      " + str(a) + "       |      " + str(b) + "      |    " + str(f(a,b)) + "    " )
    print("------------------------------------------------------------------")

#print(f(a,b))