# -*- coding: utf-8 -*-
"""Quiz4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10sVJvcofPfdnTC80CSZooAM9eFm8pAE0
"""
def AND (a,b):
  if a == True and b == True :
    return(True)
  else :
    return(False)

def OR (a,b):
  if a == False and b == False :
    return(False)
  else :
    return(True)

def NOT (a,b):
  if a == False :
    return(True)
  elif a == True :
    return(False)
  elif b == False :
    return(True)
  elif b == True :
    return(False)

def NAND (a,b):
  if a == True and b == True :
    return(False)
  else :
    return(True)

def XOR (a,b):
  if a == True and b == True :
    return(False)
  elif a == False and b == False :
    return(False)
  else :
    return(True)

def NXOR (a,b):
  if a == True and b == True :
    return(True)
  elif a == False and b == False :
    return(True)
  else :
    return(False)

def NOR (a,b):
  if a == False and b == False :
    return(True)
  else :
    return(False)

x = input("What logic do you want to check? : ")
#a = True
#b = True

print("The Truth Table")
print("------------------------------------------------------------------")
print("|        a        |        b       |       ",x , " ")
print("------------------------------------------------------------------")
for a in [True,False]:
  for b in [True,False]:
    #print("|      " + str(a) + "       |      " + str(b) + "      |    " + str(f(a,b)) + "    " )
    print('|{0:^16}|{1:^16}|{2:^16}'.format('a','b', x))

#print(f(a,b))